make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C ./tests/pkg_libschc test
test_compiled_unittests (__main__.TestCompiledUnittests) ... ok
test_compress_rule_2_down (__main__.TestFragmentation) ... ok
test_compress_rule_2_up (__main__.TestFragmentation) ... ok
test_decompress_rule_2_down (__main__.TestFragmentation) ... ok
test_decompress_rule_2_up (__main__.TestFragmentation) ... ok
test_compress_init_parse_error (__main__.TestSelfTest) ... ok
test_compress_init_success (__main__.TestSelfTest) ... ok
test_compress_no_input (__main__.TestSelfTest) ... ok
test_compress_success (__main__.TestSelfTest) ... ok
test_compress_usage (__main__.TestSelfTest) ... ok
test_compress_wrong_device_id (__main__.TestSelfTest) ... ok
test_decompress_no_input (__main__.TestSelfTest) ... ok
test_decompress_success (__main__.TestSelfTest) ... ok
test_decompress_usage (__main__.TestSelfTest) ... ok
test_fragment_init (__main__.TestSelfTest) ... ok
test_fragment_no_input (__main__.TestSelfTest) ... ok
test_fragment_no_rule (__main__.TestSelfTest) ... ok
test_fragment_success_ack_always_001 (__main__.TestSelfTest) ... ok
test_fragment_success_ack_always_all1 (__main__.TestSelfTest) ... ok
test_fragment_success_ack_on_error_10 (__main__.TestSelfTest) ... ok
test_fragment_success_ack_on_error_all1 (__main__.TestSelfTest) ... ok
test_fragment_success_no_ack (__main__.TestSelfTest) ... ok
test_fragment_success_no_frag (__main__.TestSelfTest) ... ok
test_fragment_usage (__main__.TestSelfTest) ... ok
test_input_add (__main__.TestSelfTest) ... ok
test_input_add_full_buf_mod_128 (__main__.TestSelfTest) ... ok
test_input_add_full_buf_not_mod_128 (__main__.TestSelfTest) ... ok
test_input_reset (__main__.TestSelfTest) ... ok
test_input_usage (__main__.TestSelfTest) ... ok
test_output_copy (__main__.TestSelfTest) ... ok
test_output_show (__main__.TestSelfTest) ... ok
test_output_usage (__main__.TestSelfTest) ... ok
test_reassemble_no_frag (__main__.TestSelfTest) ... ok
test_reassemble_no_input (__main__.TestSelfTest) ... ok
test_reassemble_success_ack_always (__main__.TestSelfTest) ... ERROR
test_reassemble_success_no_ack (__main__.TestSelfTest) ... ERROR
test_reassemble_usage (__main__.TestSelfTest) ... ok
test_set_ack_success (__main__.TestSelfTest) ... ok
test_set_ack_too_large (__main__.TestSelfTest) ... ok
test_set_ack_usage (__main__.TestSelfTest) ... ok
test_timer_success (__main__.TestSelfTest) ... ok

======================================================================
ERROR: test_reassemble_success_ack_always (__main__.TestSelfTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/RIOT/RIOT/tests/pkg_libschc/tests/01-run.py", line 657, in test_reassemble_success_ack_always
    self.input(b"\x17\x73\x14\xc8\x77\xf4\xe4\x00\x00\x00\x00")
  File "/home/runner/work/RIOT/RIOT/tests/pkg_libschc/tests/01-run.py", line 41, in input
    self.spawn.expect_exact("Successfully added to input buffer")
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pexpect/spawnbase.py", line 421, in expect_exact
    return exp.expect_loop(timeout)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f214f7f4be0>
command: /usr/bin/make
args: [b'/usr/bin/make', b'cleanterm']
buffer (last 100 chars): 'nd not found: idd314c877f4e400\r\n> '
before (last 100 chars): 'uccessfully reset input buffer.\r\n> idd314c877f4e400\r\r\nshell: command not found: idd314c877f4e400\r\n> '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 181823
child_fd: 5
closed: False
timeout: 10
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: 'Successfully added to input buffer'

======================================================================
ERROR: test_reassemble_success_no_ack (__main__.TestSelfTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/RIOT/RIOT/tests/pkg_libschc/tests/01-run.py", line 616, in test_reassemble_success_no_ack
    self.input(
  File "/home/runner/work/RIOT/RIOT/tests/pkg_libschc/tests/01-run.py", line 41, in input
    self.spawn.expect_exact("Successfully added to input buffer")
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pexpect/spawnbase.py", line 421, in expect_exact
    return exp.expect_loop(timeout)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f214f7f4be0>
command: /usr/bin/make
args: [b'/usr/bin/make', b'cleanterm']
buffer (last 100 chars): 'nput buffer.\r\n> input add 157fa000'
before (last 100 chars): 'ialized\r\n> reassemble 1 100\r\r\n> input reset\r\r\nSuccessfully reset input buffer.\r\n> input add 157fa000'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 181823
child_fd: 5
closed: False
timeout: 10
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: 'Successfully added to input buffer'

----------------------------------------------------------------------
Ran 41 tests in 135.345s

FAILED (errors=2)
make: *** [/home/runner/work/RIOT/RIOT/makefiles/tests/tests.inc.mk:26: test] Error 1

Return value: 2
